class AddAndChangeParticipantLocators:
    FIRSTNAME = '//html/body/div/form/div[1]/div[1]/div[1]/div/input'
    LASTNAME = '//html/body/div/form/div[1]/div[1]/div[2]/div/input'
    STACK = '//html/body/div/form/div[1]/div[2]/div[1]/div/input'
    LIST_SPECIALITY = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div/div[1]'
    DESIGN = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[1]/div'
    BACKEND = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[2]/div'
    FRONTEND = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[3]'
    QA = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[4]'
    SEO = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[5]'
    PM = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[6]'
    NONE = '//html/body/div/form/div[1]/div[2]/div[2]/label/div/div[2]/div/div[7]'
    # EXPERIENCE_TRUE = '//html/body/div/form/div[1]/div[3]/div[1]/label/div/div[2]/div/div[1]'
    LIST_EXPERIENCE = '//html/body/div/form/div[1]/div[3]/div[1]/label/div/div/div[1]'
    EXPERIENCE_TRUE = '#react-select-experience-option-0'
    EXPERIENCE_FALSE = '#react-select-experience-option-1'
    LIST_TYPE_PARTICIPANTS = '//html/body/div/form/div[1]/div[3]/div[2]/label/div/div/div[1]'
    TYPE_PARTICIPANT_FREE = '//html/body/div/form/div[1]/div[3]/div[2]/label/div/div[2]/div/div[1]'
    TYPE_PARTICIPANT_PAY = '//html/body/div/form/div[1]/div[3]/div[2]/label/div/div[2]/div/div[2]'
    TYPE_PARTICIPANT_BOOTCUMP = '/html/body/div/form/div[1]/div[3]/div[2]/label/div/div[2]/div/div[3]'
    CITY = '//html/body/div/form/div[1]/div[4]/div[1]/div/input'
    COMMENT = '//html/body/div/form/div[1]/div[4]/div[2]/div/input'
    BUTTON_SEND_LETTER = '//html/body/div/form/div[2]/div[1]/button'
    DISCORD = '//html/body/div/form/div[2]/div[2]/div[1]/div/input'
    LINKEDIN = '//html/body/div/form/div[2]/div[2]/div[2]/div/input'
    PHONE_NUMBER = '//html/body/div/form/div[2]/div[3]/div[1]/div/input'
    EMAIL = '//html/body/div/form/div[2]/div[3]/div[2]/div/input'
    BUTTON_ADD_PROJECT = '//html/body/div/form/div[3]/div[1]/button'
    BUTTON_SAVE_CHANGES = '//*[@id="bigFontBtn"]'
    BUTTON_SAVE_CHANGES_IN_CHANGE_PARTICIPANT = '/html/body/div/form/div[4]/button[1]'
    BUTTON_DONT_SAVE_CHANGES = '//html/body/div/form/div[4]/button[2]'
    BUTTON_LIST_PROJECT = '/html/body/div/form/div[3]/div[2]/div/label/div/div/div[1]/div[2]'
    BUTTON_DELETE_PROJECT = '/html/body/div/form/div[3]/div[2]/button/svg'

